### ISSUE TITLE
Check for updates to mtgjson automatically

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2416]
Some of you might now "Thicket", an application for drafting.
The developer stopped by in our gitter a few times.
I tested it once and just opened it again to realize it has a very sweet way of automatic update checking, info dialogs and a nice and simple way to guide the user. It's also built with Qt...
![thicket-newversion](https://cloud.githubusercontent.com/assets/9874850/23094310/b6e972b8-f5f6-11e6-851b-e24f8ea7eed5.png)
![thicket-newmtgjson pn](https://cloud.githubusercontent.com/assets/9874850/23094313/b904d63c-f5f6-11e6-9a9f-dc5fed9705a7.png)

Maybe @mildmongrel wants to walk us through his update checking and download process concept?

Github: https://github.com/mildmongrel/thicket
CC: @ctrlaltca 

---

TODO as lined out by @ctrlaltca in https://github.com/Cockatrice/Cockatrice/issues/2416#issuecomment-283288234:

- [ ] automated or at least better manual update checks
- [ ] better handling of mtgjson and token updates
- [x] use the github api to determine if there are newer versions available #2362
- [x] different release channels #2362
- [x] missing link to the changelog #2362

**Comment by mildmongrel** [comment]
Sure, no problem.  The Thicket client checks for client updates and for MTG JSON updates and they're handled a bit differently.  Not sure what the context of this discussion is so I'll talk about client updates, they're easier.  :)

Thicket is Qt-based but these updates actually rely on a separate web service running a very simple node.js server.  On every release I update the web service with the latest version and a link to where to download it.

The Thicket client is has its version number built-in.  On startup (or via menu option), the client queries the web service with its current version as a parameter.  The web service checks if its version is newer (making use of the 'semver' module) and returns a simple JSON response that indicates if an update is available and the link.  The client displays the link and that's that - the user can download and install from there.  I don't handle auto-upgrading. etc.

Client side: https://github.com/mildmongrel/thicket/blob/master/client/ClientUpdateChecker.cpp
Web service side: https://github.com/mildmongrel/thicket/blob/master/web/thicket.js

**Comment by Daenyth** [comment]
It sounds like the node server portion is what we don't have right now. We're basically just listing releases from bintray directly and examining filenames.

Is there a specific part of the current upgrade process you'd like to make smoother @tooomm ?

**Comment by tooomm** [comment]
@mildmongrel Right now we have manual checks in place. In order to improve the user experience, it might help to have some automated or at least better manual checks. At the moment we don't check for mtgjson or tokens updates at all! People have to manually run oracle and overwrite their files, there is no check at all for changes/updates - so it's not smart at the moment.
You could update the card database like 5 times in a row, since we just download the complete `AllSets.json.zip` file, process it and override our database. :)

That's why the update process for mtgjson is actually more interesting I think...
Since we don't have that server at the moment and updates to the card file are more critical and people demand quick updates a lot here!

I know that mtgjson publishes the current version number:
- as quoted string: http://mtgjson.com/json/version.json
- and as json object: http://mtgjson.com/json/version-full.json

Can we compare this number to our local database? (Oracle needs to write its source version for sure)

We could host a version file on our **token** repo as well and check it for updates and trigger a new **download within the client (without forcing the user to go through all oracle steps... we don't need to process the token file, we just download it!?)**.
Quick updates and fixes for mtgjson and the tokens are key basically.
People always keep asking when things will get fixed or new sets are implemented...
I think this is more important than having an automated check for client updates right now.
*I can also imagine that each server sends the newest version numbers for cards/tokens that the server is used for on login and the client deals with the rest to lower the amount of individual queries... if there is a need for that.*

<br>
About the client updates...

Can't we use the github api or the github newsfeed to determine if there are newer versions available instead of having a web service running on a server?
- Github API
https://api.github.com/repos/cockatrice/cockatrice/releases/latest
- Newsfeed
https://github.com/cockatrice/cockatrice/releases.atom

Zach also had this idea with checking for new commit count as escribed here: https://github.com/Cockatrice/Cockatrice/pull/2362#issuecomment-272700564

<br>

>Is there a specific part of the current upgrade process you'd like to make smoother @tooomm ?

If we get the release channels working with e.g. like main, rc and development or main, beta and alpha this is a great improvement.
All other issues regarding updating are mostly filed, like a missing link to the changelog from within the update message, the infinite update loop or a better naming scheme.
**But a better handling of mtgjson or token updates is not covered at the moment!** (well, besides https://github.com/Cockatrice/Cockatrice/issues/1364 i think)

**Comment by ctrlaltca** [comment]
Todo:
> In order to improve the user experience, it might help to have some automated or at least better manual checks.

> But a better handling of mtgjson or token updates is not covered at the moment! (well, besides #1364 i think)

Implemented/fixed in https://github.com/Cockatrice/Cockatrice/pull/2362 :

> About the client updates... Can't we use the github api or the github newsfeed to determine if there are newer versions available instead of having a web service running on a server?

> If we get the release channels working with e.g. like main, rc and development or main, beta and alpha this is a great improvement.

> All other issues regarding updating are mostly filed, like a missing link to the changelog from within the update message, the infinite update loop or a better naming scheme.

**Comment by ctrlaltca** [comment]
Closing this issue since the remaining points are basically a duplicate of #2924 and #3647
