### ISSUE TITLE
[RFC] Spoiler Handling

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2764]
Spoilers are a type of custom set that is popular on Cockatrice servers. During the weeks leading up to a set release, Wizards and their affiliates provide images of cards for players to discuss, speculate, and test with. Many Cockatrice users like to get testing immediately and to facilitate this, custom XML files are created containing the spoiled cards.

In an effort to improve quality and centralize the spoilers, Cockatrice developers have created the [Magic-Spoiler](https://github.com/Cockatrice/Magic-Spoiler) repository. This repository is designed to scrape some of the sites that compile the spoilers as they are realized, as well as manually entering cards leveraging git and GitHub functionality to create a Cockatrice friendly XML file. (Some preliminary discussion in #2622)

This thread is to discuss and improve the way that Cockatrice handles these "unique" custom sets. Much of the custom set handling code is designed for user-created cards that are not frequently updated and do not expire (as spoilers effectively do when the set is released and added to mtgjson.)

Current possible issues with the custom set handling code in regards to spoilers (or overall):

- [x] 1. Using `Add custom sets/cards` creates duplicate set files instead of updating if set/spoiler exists
--> #2784
- [x] 2. Only way to 'clear' spoiler XML at end of season (mtgjson update) is to open folder and delete files via OS
- [x] 3. Not possible to see if spoiler file is newer than current
- [ ] 4. Customsets folder is not configurable
- [x] 5. If spoiler file exists for a set, running oracle and importing the same set from mtgjson will not prompt user to add set (related #2712)
- [ ] 6. If an improved (English, higher resolution or better quality) image for a card is found and updated in the spoiler file and this new file gets used in trice, Cockatrice still maintains the original image until deleted via entire image wipe or manual OS delete
- [ ] 7. After mtgjson updates, images from XML that exist are still used instead of gatherer or image source

**Comment by tritoch** [comment]
Adding some meta data to the XML file will assist in some of these items:

1 & 3:
Should have a created date/time, and overwrite file if set code exists and created date is newer. Cockatrice can then check spoiler file against the same file in customsets for the created date/time.

2, 4, 5, 7:
A `<spoiler="True">` key would allow Cockatrice to check if file/set is a spoiler, and then if it exists in mtgjson, prompt (and recommend) you to delete the spoiler file and any downloaded pics, and then perform that action.

**Comment by Daenyth** [comment]
6 could be improved generally by adding some image management - view all images for cardname, delete specific images for cardname, delete images for set, delete all images

**Comment by tooomm** [comment]
The images... yes... (6+7)

Most important here are 1,2,3 and 5 I guess.
While 4 might be the easiest to address.

**Comment by Daenyth** [comment]
Can you elaborate about what isn't configurable? Disk location?

**Comment by tooomm** [comment]
Yes, I think he is referring to that. You can configure some in settings, bot not the custom sets or pics.
Pics might change if you adjust the path to pictures, which you can do in settings!
(that "open custom image folder" menu entry is still broken on windows though)

**Comment by tooomm** [comment]
1. I basically solved with #2784 now - not smart yet though, since there is no check for version/date as mentioned here: https://github.com/Cockatrice/Cockatrice/issues/2764#issuecomment-307856785
 
<br>

after talking on gitter i came up with this idea:

6. >I wouldn't care too much about "lower" quality spoiler pics which gets replaced with better ones... because from mtgs they are basically all quite good. Also mtgs doesn't have foreign card pics and we use it as the default priority.  

7. >Cocktrice could have a special `/spoiler` folder in `pics` somewhere and we delete the subfolder of the set just there (`/spoiler/hou` for example). Because if it's in mtgjson afterwards, we would look in the normal `pics/downloadedPics/hou` folder instead.

**Comment by tritoch** [comment]
(2) is also assisted by #2784. The Magic-Spoiler project will make an effort to clear out the set data when mtgjson updates, so bringing in a spoiler.xml with that data cleared and overwriting current will remove that set from database.

**Comment by ZeldaZach** [comment]
Question on the relevance of this PR ever since the #2991 PR

**Comment by tooomm** [comment]
5+7 should be fixed with #2991, yes.

4+6 remain unchecked. 6 would improve with https://github.com/Cockatrice/Cockatrice/issues/2838

**Comment by ZeldaZach** [comment]
Dupe of the #4109
