### ISSUE TITLE
Backup from former TODO file

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2871]
Notable mentions:
- [ ] Write example init script for servatrice
- [ ] Update SFMT library in common/sfmt and adapt common/rng_sfmt.cpp
(http://www.math.sci.hiroshima-u.ac.jp/~m-mat@math.sci.hiroshima-u.ac.jp/MT/SFMT/)
- [ ] Move hardcoded URLs (especially from oracle and cockatrice) into a config file.
- [ ] More and better developer documentation (code comments, component descriptions and interactions)

---
Original content:

```
# TODOs

This is an unordered list of possible todo items for Cockatrice.
Note that "improve" and "write" always also means: "document and comment"

## Improve packaging:
* Improve nsis file git hash extraction, it only works if the build directory is cleared as version_string.cpp does not seem to get updated by git pull/cmake
* Create script/... for creating Linux packages (deb, rpm, ebuild, ...) or at least an official tarball/git tags; package maintainers dislike using git snapshots so much that they rather ignore software without stable tarballs.

## Scripts
* Write example init script for servatrice.

## Create developer documentation:
* Create developer manual
* Add comments to code
* Describe which components exist and how they work and interact
* Describe the *.proto files
* Comment and document servatrice.sql
* Document everything!1!!

## Else

* Update SFMT library (http://www.math.sci.hiroshima-u.ac.jp/~m-mat@math.sci.hiroshima-u.ac.jp/MT/SFMT/) in common/sfmt and adapt common/rng_sfmt.cpp

* Move hardcoded URLs (especially from oracle and cockatrice) into a config file.

* Search git log for useful information/problems/bugs/...
```
Source: https://github.com/Cockatrice/Cockatrice/blob/dd36187864644c9dbed9cb787137faaa84c1f95e/TODO.md
