### ISSUE TITLE
icons8 TODO

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3255]
Checklist *icons8*

- [x] Signup an account at https://icons8.com/
- [x] Tell support the account mail address to receive license
- [ ] Decide which icons we want to use (#3256)
- [ ] :shipit: 

CC @Daenyth

**Comment by Daenyth** [comment]
do I email support or should you @tooomm? I used my daenyth@gmail to sign up

**Comment by tooomm** [comment]
I feel like this ticket is not really needed anymore, the other one should be enough for discussion on particular icons.
