### ISSUE TITLE
LONG list of suggestions compiled over months

### ISSUE THREAD

**Issue by ray73neo** [Cockatrice/Cockatrice#655]
- [ ] In-game:
  - [ ] 1) Pressing Enter brings up the chat
  - [x] 2) Ctrl+Click to individually select multiple cards, rather than relying only on Box select
  - [ ] 3) Make the turn indicator more visible by making it a different color (red or yellow maybe)
  - [ ] 4) Different in-game messages for a player getting disconnected and for closing his/her client, so you know if they quit or if they simply have network issues
  - [x] 5) Different in-game messages for a player getting kicked/leaving
  - [x] 6) Side-scroll bar in Players list removed (unnecessarily takes up screen space)
  - [x] 7) Top card no longer revealed when it is toggled off (currently stays revealed until refreshed)
  - [ ] 8) Right-clicking a a player's avatar in-game gives dropdown menu (User details, Show user's games, Add to buddy list, etc)
  - [x] 9) Different colors for player usernames in chat
  - [x] 10) When setting a card's counters via "Set counters (geen)" the default value appears as the current number of counters on it (similar to how setting life with ctrl+L currently functions)
  - [ ] 11) Right-click a token card to add it to your premade tokens
- [ ] Ability to:
  - [x] 12) Reassign hotkeys - dupe #130 
  - [x] 13) Send offline players messages - dupe #1744
  - [x] 14) Block unregistered users
  - [ ] 15) Blocking a player blocks him/her from joining or spec'ing your games, and hides them on the list of the lobbies
  - [ ] 16) Start the game even when the game lobby is not full
  - [x] 17) Kick players who have lost connection to the game via their usernames in the chatbox (currently bugged, not working)
  - [ ] 18) Rename game rooms and edit game settings if you are hosting the lobby (ex. Spectator settings, passworded or publicly accessible, set to only registered users or not, 
  - [x] 19) View your own games by right clicking -> Show games
  - [ ] 20) "Show this user's games" should give the option to show which players are present in a game without joining it
  - [x] 21) Tag buddies with a note to remind you who they are, what formats they like to play, etc. (for players with many buddies) - dupe #1384
- [ ] Useful for EDH:
  - [x] 22) ~~Player life totals  start at 40 by default in EDH games~~
  - [x] 23) P/T background a dark grey rather than black, to contrast from the card's name when they overlap
  - [ ] 24) Same goes for annotations
  - [ ] 25) Hovering the mouse over a player's avatar displays it enlarged on the right side along with their life points (will give a clearer view of players' avatars that are square shaped)
  - [x] 26) Option to hide card name
  - [ ] 27) Middle-clicking a card shows a creature's current Power/Toughness, annotations, counters, and Token's name
- [ ] Chat Room / Game Lobby:
  - [x] 28) Unregistered players can see open lobbies set for registered players only, to encourage them to register
  - [x] 29) Search filters do not reset when logging off
  - [x] 30) Resizing the columns in the list of available games does not reset when logging off - dupe #2152
  - [x] 31) Check a box when creating a new game that says, "Remember lobby settings" which keeps the game name and settings for next time, including the order-by category
  - [x] 32) Display which spectator settings are set for a game (specs can chat / see everything) when browsing games
  - [ ] 33) Color-coded tabs for User Lists, Chat Room, and Game for easy identification (and also hotkeys to jump to a particular tab)
  - [x] 34) "Creator"  criteria when viewing the list of game lobbies -> replaced with "Host"  and is updated accordingly when the original game creator leaves the room - dupe #2108
  - [ ] 35) Filters for "buddies only" games, blank game types (add "None" as a game type filter)
  - [x] 36) Filters for games that don't allow spectators, when you are looking to spectate a game - dupe #2642
- [x] Hotkeys:
  - [x] 37) Set annotation
  - [x] 38) Tap/Untap
  - [x] 39) Load Deck / Ready to Start pre-game window
  - [x] 40) +/- 1 a counter on a  card
- [ ] Misc:
  - [x] 41) ~~Player Fame, which is a score that other players can +2 or -1 to fame or defame a player. In order to encourage faming, I suggest each that each fame be worth 2 and each defame only 1~~
  - [x] 42) Notification (with optional sound) in the form of IM when a buddy logs on
  - [x] 43) Players can choose the color they want to display their usernames as in the main chat room
  - [ ] 44) Drag a card into chat to paste+link it. Can drag to other tabs (ex. Game -> Main Chat)
  - [ ] 45) Search bar to filter game lobby titles (ex. FFA, competitve)
  - [ ] 46) Choose which set's card art you would prefer
  - [ ] 47) Animation of cards when they are moved around on the board (ex. From hand to field;  library -> hand;  graveyard -> field;  stack -> field;  etc.)
  - [x] 48) Times stamp in chat (IM only, not in-game)
  - [x] 49) Notifications should blink in the tab to be more noticeable than just a green exclamation mark
  - [x] 50) When minimized, the Cockatrice client window doesn't blink when a game that you are spectating updates, only blinks when chat messages or your active game
  - [x] 51) When trying to reconnect to a disconnected game, issues from delay timer "another session in-use. Exit that one first"

**Comment by ZeldaZach** [comment]
This is a very compiled list, but the way we do it on GitHub is usually one issue w/ relevant sub-issues per ticket. I feel like this may cause issues if you do that, so maybe @Daenyth can give some insight

**Comment by Daenyth** [comment]
Some of these are useful and easy, some are useful and a pain to implement, some aren't going to be useful, and some are duplicates of existing tickets.

**Comment by tooomm** [comment]
To make this list somehow useful I gave it a closer look...

@ray73neo: about 20% of this list is already done. I suggest you update your first post with my annotations accordingly.
(you can use double "~" before and at the end of the line to make them ~~appear crossed out.~~

Fist of all you should check out the newest version from the woogerworks site.
I would recommend that always if you have any issues + suggestions. ;)

Done already:
 - 6
 - 7, 14 and 43 (settings / chat settings)
 - 9 (we got mentions if you use @username - it will change the color and make it clickable)
 - 26 (settings / appearance)
 - 29
 - 48 (it is ingame too, for a good reason I think)

Partially done:
 - 15 (ignored player can't join your game as player or spectator)
 - 46 (you can reorder the sets (deck editor -> card database -> edit sets), the ones on top will override card arts lower on the list, not customizable for individual cards though)

I don't know about open tickets matching your list. You might want to use the search to look out for them.

Someone else might give this a doublecheck.
There are some useful things in there... and some not so. :)

**Comment by ctrlaltca** [comment]
Switched the original list to a task list with checkboxes

**Comment by LestatTheDarkPrince** [comment]
I think number 41 has an issue as some players could just defame people they do not like for whatever reason.

**Comment by ZeldaZach** [comment]
@LestatTheDarkPrince They would have to dislike a user for a specific reason, so I don't see a big issue with the +2/-1 system

**Comment by LestatTheDarkPrince** [comment]
enh just saying it seems like they could find a user they hate and just
keep flamming them.

**Comment by Daenyth** [comment]
There have been many discussions over the years about a karma system; the short version is that it won't happen

**Comment by ctrlaltca** [comment]
Number 41 fixed in #3886

**Comment by ZeldaZach** [comment]
This ticket seems very painful and hurts our searches. I'm closing it as we've solved a lot of things already
