### ISSUE TITLE
Remove support for v14 server/client handshake hacks

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#850]
This was the version before protobufs which used xml instead (at least 3-4 years old).

Anyone who is using clients/servers that ancient is out of the loop to the point where they won't know to get the updated version that's not compatible

**Comment by woogerboy21** [comment]
I was looking into this briefly.  Am I understanding this hack wrong that when the client went from XML to protobuf you guys forcefully updated the XML string on the client side to say its protocol version was 14?  Was there anything else involved that I am over looking?

**Comment by Daenyth** [comment]
The client sends an XML message first, and the server ignores the first
message on the socket

**Comment by woogerboy21** [comment]
I once again attempted to look into this and remove it.  But from the way the code is written, it doesn't behave as you describe.  What I do see is an if statement in the remote client that ignores an XML block of data:

```
if (inputBuffer.size() >= 4) {
                // dirty hack to be compatible with v14 server that sends 60 bytes of garbage at the beginning
                if (!handshakeStarted) {
                    handshakeStarted = true;
                    if (inputBuffer.startsWith("<?xm")) {
                        messageInProgress = true;
                        messageLength = 60;
                    }
                } else {
                // end of hack
```

So here is what happens, the client when making it first connection does not populate the cmd_id of the container.  This is the trigger the client uses for the "handshake" that the server understands.  On the first connection the server the server appends a block of XML data to the response and ships it back to the client in turn triggering the "handshake" block of code due to the missing cmd_id in the command container.  When the client see's that XML response (or a buffer size larger than 4 and input buffer starting with <?xm) it ignores that response and triggers its own "handshake" block of code.  Once both the server and the client have flagged the "handshake" as true the command container is populated on the client side and shipped to the server and now that the session has been properly built the server does not append any XML data to the response and processes the command container accordingly.

Now I can remote the function that appends the XML data from the response and drop the block of code in the remove client that ignores it which I am assuming is what you mean by taking away the "hacks" but I'm not certain its safe to remove the initial handshake portion of the code without updating the protocol value and triggering a required client update.  Or am I wrong about the required client update?  Older clients would still be sending command containers that have no cmd_id and the server would just do nothing with the request maybe?

**Comment by Daenyth** [comment]
I think the first step would be to update the server code to accept client connections that don't send the fake handshake as well as ones that do. Then once all the servers we know of are updated to that, we can release a client update that stops sending the handshake. Then eventually we can remove the hack from the server

**Comment by tooomm** [comment]
Roadmap:
- [ ] 1. Make Servatrice accept connections of clients that don't send a fake handshake
- [ ] 2. Update Cockatrice to not send fake handshakes anymore
- [ ] 3. Remove hack from Servatrice

**Comment by ctrlaltca** [comment]
Please note that the "handshake hack" is only used on the tcp-based connections, and is not present in the websocket connections. This means this ticket will be implicitly fixed by https://github.com/Cockatrice/Cockatrice/issues/3537

**Comment by tooomm** [comment]
Oh, nice! As the transition to websockets started and all main servers offer support already, we don't need this additional process in between.

Will close this issue then and put a note in the other issue. Thanks for the hint @ctrlaltca!
